# Site settings
title: Nida Ismail Shah
email: nidaismailshah@gmail.com
description: "Some lines , a bit elaborated"
baseurl: ""
url: "http://nidaismailshah.github.io"
twitter_username: nidaismailshah
github_username:  nidaismailshah
facebook_username: nidaismail
gplus_username: +NidaIsmailShah

# Build settings
markdown: kramdown
permalink: pretty
